#!/usr/bin/env bash
# Repoints the kaleido-api worker (the permanent public API URL at
# https://kaleido-api.goblin-anwar.workers.dev) at the current quick
# tunnel URL. Run automatically by start-kaleido.sh after the tunnel starts.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CF_API_TOKEN=$(grep -E "^CF_API_TOKEN=" "$ROOT/kaleido-backend/.env" | cut -d= -f2-)
CF_ACCOUNT_ID=$(grep -E "^CF_ACCOUNT_ID=" "$ROOT/kaleido-backend/.env" | cut -d= -f2-)
if [ -z "$CF_API_TOKEN" ] || [ -z "$CF_ACCOUNT_ID" ]; then
  echo "update-api-proxy: CF_API_TOKEN or CF_ACCOUNT_ID missing in kaleido-backend/.env" >&2
  exit 1
fi

URL=$(grep -oE "https://[a-z0-9-]+\.trycloudflare\.com" "$ROOT/logs/cloudflared.log" | tail -1)
if [ -z "$URL" ]; then
  echo "update-api-proxy: no tunnel URL found in logs/cloudflared.log" >&2
  exit 1
fi

WORKER=$(mktemp)
cat > "$WORKER" <<EOF
// Permanent public API address for Kaleido.
// Forwards everything to the backend tunnel; this file is generated by
// update-api-proxy.sh whenever the tunnel URL changes.
const ORIGIN = "$URL";

export default {
  async fetch(request) {
    const url = new URL(request.url);
    return fetch(new Request(ORIGIN + url.pathname + url.search, request));
  },
};
EOF

RESULT=$(curl -s -X PUT -H "Authorization: Bearer $CF_API_TOKEN" \
  "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/kaleido-api" \
  -F 'metadata={"main_module":"worker.js","compatibility_date":"2025-01-01"};type=application/json' \
  -F "worker.js=@$WORKER;filename=worker.js;type=application/javascript+module")
rm -f "$WORKER"

if echo "$RESULT" | grep -q '"success": *true'; then
  echo "update-api-proxy: worker now points at $URL"
else
  echo "update-api-proxy: deploy failed: $RESULT" >&2
  exit 1
fi
