"""add analytics tables

Revision ID: 47a28b157c27
Revises: 164810a64211
Create Date: 2026-04-06 21:16:29.257789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a28b157c27'
down_revision: Union[str, Sequence[str], None] = '164810a64211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('followers_count', sa.BigInteger(), nullable=False),
    sa.Column('following_count', sa.BigInteger(), nullable=False),
    sa.Column('posts_count', sa.BigInteger(), nullable=False),
    sa.Column('total_reach', sa.BigInteger(), nullable=False),
    sa.Column('total_impressions', sa.BigInteger(), nullable=False),
    sa.Column('total_engagement', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('extra_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_collected_at'), 'analytics_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_platform'), 'analytics_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_social_account_id'), 'analytics_snapshots', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_table('post_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('saves', sa.BigInteger(), nullable=False),
    sa.Column('reach', sa.BigInteger(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('extra_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['post_publications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_analytics_collected_at'), 'post_analytics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_post_analytics_platform'), 'post_analytics', ['platform'], unique=False)
    op.create_index(op.f('ix_post_analytics_post_id'), 'post_analytics', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_analytics_user_id'), 'post_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_analytics_user_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_post_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_platform'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_collected_at'), table_name='post_analytics')
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_social_account_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_platform'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_collected_at'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
