"""create brands table

Revision ID: 7fa60c40c977
Revises: c3855d04bf9e
Create Date: 2026-04-06 20:16:46.568275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa60c40c977'
down_revision: Union[str, Sequence[str], None] = 'c3855d04bf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('color_primary', sa.String(length=7), nullable=True),
    sa.Column('color_secondary', sa.String(length=7), nullable=True),
    sa.Column('color_accent', sa.String(length=7), nullable=True),
    sa.Column('brand_voice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dos_and_donts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
